export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCSS";

export const FETCH_SINGLE_CATEGORY = "FETCH_CATEGORY";
export const FETCH_SINGLE_CATEGORY_SUCCESS = "FETCH_SINGLE_CATEGORY_SUCCESS";
