export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCSS";

export const FETCH_SINGLE_CATEGORY = "FETCH_CATEGORY";
export const FETCH_SINGLE_CATEGORY_SUCCESS = "FETCH_SINGLE_CATEGORY_SUCCESS";

export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const CHANGE_TAB = "CHANGE_TAB";
