export const STORE_TOKEN = "STORE_TOKEN";
export const LOG_OUT = "LOG_OUT";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
