export const CURRENTLY_LOADING = "CURRENTLY_LOADING";
export const LOADING_COMPLETED = "LOADING_COMPLETED";

export const SHOW_SEARCH_BAR = "SHOW_SEARCH_BAR";
export const HIDE_SEARCH_BAR = "HIDE_SEARCH_BAR";

export const SET_EXTRACTED_COLOR = "SET_EXTRACTED_COLOR";
export const RESET_COLOR = "RESET_COLOR";
