export const GET_USERS_TOP_ITEMS = "GET_USERS_TOP_ITEMS";
export const GET_USERS_TOP_ITEMS_SUCCESSFUL = "GET_USERS_TOP_ITEMS_SUCCESSFUL";

export const GET_FEATURED_PLAYLISTS_SUCCESS = "GET_FEATURED_PLAYLISTS_SUCCESS";
export const GET_NEW_RELEASES_SUCCESS = "GET_NEW_RELEASES_SUCCESS";
